# Generated by Django 5.0.14 on 2026-07-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0002_inquiry_batch_id_inquiry_customer_inquirycartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('replied', 'Replied'), ('confirmed', 'Confirmed'), ('closed', 'Closed')], default='pending', max_length=20),
        ),
    ]
