# Generated by Django 5.0.14 on 2026-06-27 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('fabric', models.CharField(choices=[('silk', 'Silk'), ('cotton', 'Cotton'), ('georgette', 'Georgette'), ('chiffon', 'Chiffon')], db_index=True, max_length=20)),
                ('color', models.CharField(choices=[('red', 'Red'), ('maroon', 'Maroon'), ('pink', 'Pink'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('gold', 'Gold'), ('green', 'Green'), ('blue', 'Blue'), ('navy_blue', 'Navy Blue'), ('purple', 'Purple'), ('black', 'Black'), ('white', 'White'), ('cream', 'Cream'), ('grey', 'Grey'), ('multicolor', 'Multicolor')], db_index=True, max_length=20)),
                ('border_color', models.CharField(blank=True, choices=[('red', 'Red'), ('maroon', 'Maroon'), ('pink', 'Pink'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('gold', 'Gold'), ('green', 'Green'), ('blue', 'Blue'), ('navy_blue', 'Navy Blue'), ('purple', 'Purple'), ('black', 'Black'), ('white', 'White'), ('cream', 'Cream'), ('grey', 'Grey'), ('multicolor', 'Multicolor')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('sold_out', 'Sold Out'), ('hidden', 'Hidden'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='products/%Y/%m/')),
                ('is_primary', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'ordering': ['-is_primary', 'created_at'],
            },
        ),
    ]
